# tests/test_writer_agent.py
"""Offline tests for WriterAgent (LLM calls are stubbed)."""
from datetime import date

import pytest

from src.agents.writer_agent import WriterAgent


@pytest.fixture
def agent(llm_model):
    return WriterAgent()


@pytest.mark.asyncio
async def test_load_context_reads_summary(agent, tmp_path):
    path = tmp_path / "summary.md"
    path.write_text("# Digest\n\nStuff happened.")

    assert await agent._load_context(str(path)) == {"summary": "# Digest\n\nStuff happened."}


@pytest.mark.asyncio
async def test_process_sends_summary_to_llm(agent, monkeypatch):
    prompts = []
    monkeypatch.setattr(agent, "_call_llm",
                        lambda prompt: prompts.append(prompt) or "Newsletter body")

    result = await agent._process({"summary": "LLM news summary"})

    assert result == {"newsletter": "Newsletter body", "date": date.today().isoformat()}
    assert "LLM news summary" in prompts[0]


@pytest.mark.asyncio
async def test_save_result_writes_newsletter(agent, tmp_path):
    output = tmp_path / "output" / "newsletter.md"

    await agent._save_result({"newsletter": "Hello readers!", "date": "2026-10-03"}, str(output))

    content = output.read_text()
    assert content.startswith("# AI/ML Daily Newsletter - 2026-10-03\n\nHello readers!")
    assert content.rstrip().endswith("*Generated by AI Agent Pipeline*")


@pytest.mark.asyncio
async def test_execute_end_to_end(agent, monkeypatch, tmp_path):
    monkeypatch.setattr(agent, "_call_llm", lambda prompt: "Today in AI...")
    summary = tmp_path / "summary.md"
    summary.write_text("## LLM (2 articles)\n\nBig week.")
    output = tmp_path / "newsletter.md"

    result = await agent.execute(str(summary), str(output))

    assert result == {"input_path": str(summary), "output_path": str(output), "success": True}
    assert "Today in AI..." in output.read_text()
